export const text = [
  "We are 100 Shapes.",
"Our tone of voice captures our personality and represents it in language.",
"We are experts in our field, have an opinion on our craft, and are ambitious; but always humble, because we know there’s always more to learn.",
"We don’t preach, we are conversation starters.",
"We are curious about making things better, we ask questions, we want to hear your side – we never alienate.",
"We write like we talk – simply and with clarity; we never use a long word where a short one will do.",
"We have purpose, but also spirit.",
"We draw you into our story, a seamless extension of your own.",
"Familiar and comforting – you know your future is in safe hands, but with the promise of something unexpected.",
"We have an infectious energy that sparks a curiosity to explore the new and undiscovered.",
"We are purposeful.",
"We are storytellers.",
"We are energizers.",
"We are curious about how we can do things smarter.",
"We ask meaningful questions, always with a clear vision and a desire to make a difference.",
"We always put people at the heart of what we do.",
"We take the time to listen, so others feel comfortable to be themselves, and supported to succeed.",
"We strive for exceptional in everything that we do, taking the smart route, not the easy one.",
"We are united in our determination to create meaningful change, taking pride in making long-lasting impact.",
"Be passionately curious.",
"We never stop learning.",
"Being curious about design empowers us to solve problems with fresh thinking.",
"Each project is a chance to crack a new code.",
"We yearn for that moment of uncovering the final puzzle piece, that sweet bit of insight that will help us create something better, smarter.",
"We aren’t only curious about design, but about our users, our peers, and our clients.",
"We ask meaningful questions, we think, we ponder, and we act.",
"Always with a clear vision and a desire to make a difference.",
"Have fun, together.",
"Creativity is purposeful play.",
"So whether through project discovery, user workshops, or our daily team lunch, we make time to connect and create.",
"Good design is about understanding people.",
"We know we do our best work when we can be ourselves, so we’re always empathetic and respectful of opinions that are different to our own.",
"Fantastic teams are made up of empowered individuals.",
"We have the freedom to develop in a direction that is true to us, but also be there for others when they need us; sharing our skills, lending a hand, or reflecting over pizza.",
"Leave a meaningful mark.",
"We bring the expertise to prepare for the future.",
"Often, growth is fast, and we need to make changes, faster.",
"We’re always thinking ahead, figuring out how to make the most purposeful impact.",
"We take a step back before starting a project, taking time to figure out the smart approach, not the easy one.",
"We take pride in making an impact, with long-lasting benefits.",
"Our readiness for the future means we are confident in our ability to make change.",
"We are at the heart of shaping the future of design, raising a new bar for our clients, our peers and our industry."
]
